export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: '$19',
    period: '/month',
    description: 'Start monitoring real buying signals with enough coverage to prove the workflow.',
    features: [
      '5 keyword monitoring rules',
      'Up to 250 buyer-intent signals/month',
      '40 AI-drafted replies/month',
      'Manual review and send workflow',
      'Reddit & Bluesky monitoring',
    ],
    cta: 'Start with Starter',
    href: '/signup?plan=starter',
    highlight: false,
  },
  {
    id: 'pro',
    name: 'Professional',
    price: '$49',
    period: '/month',
    description: 'For founders actively working a social selling motion.',
    features: [
      'Everything in Starter',
      '10 keyword monitoring rules',
      'Up to 1,000 buyer-intent signals/month',
      '400 AI-drafted replies/month',
      'Reddit & Bluesky monitoring',
      'Guarded auto-send',
      'Subreddit targeting',
      'Slack notifications and reply attribution',
    ],
    cta: 'Upgrade to Professional',
    href: '/signup?plan=pro',
    highlight: true,
  },
  {
    id: 'growth',
    name: 'Growth',
    price: '$149',
    period: '/month',
    description: 'For teams that need higher limits and faster monitoring.',
    features: [
      'Everything in Professional',
      '50 keyword monitoring rules',
      'Up to 5,000 buyer-intent signals/month',
      '2,000 AI-drafted replies/month',
      '5-minute polling cadence',
      'Guarded auto-send',
      'Reply attribution and trust analytics',
    ],
    cta: 'Upgrade to Growth',
    href: '/signup?plan=growth',
    highlight: false,
  },
] as const
